CREATE TABLE BOOKS (
    EVT_ID        NUMBER(19)   NOT NULL,
    BU_ID         NUMBER(19)   NULL,
    EVT_STATUS_ID NUMBER(19)   NULL,
    VERI_DATE     DATE         NULL,
    BOOK_DATE     DATE         NULL,
    VAL_DATE      DATE         NULL,
    TRX_DATE      DATE         NULL,
    PERF_DATE     DATE         NULL,
    CONSTRAINT PK_BOOKS PRIMARY KEY (EVT_ID)
);

CREATE TABLE EVT_PKT (
    EVT_ID         NUMBER(19)   NOT NULL,
    PKT_SEQ_NR     NUMBER(19)   NOT NULL,
    POS_ID         NUMBER(19)   NULL,
    BOOK_KIND_ID   NUMBER(19)   NULL,
    QTY            NUMBER(38,10) NULL,
    EXTL_BOOK_TEXT VARCHAR2(4000) NULL,
    CONSTRAINT PK_EVT_PKT PRIMARY KEY (EVT_ID, PKT_SEQ_NR),
    CONSTRAINT FK_EVT_PKT_BOOKS
        FOREIGN KEY (EVT_ID) REFERENCES BOOKS (EVT_ID)
);
